### ISSUE TITLE
feat (connect-nodejs): NodeJS Implementation

### ISSUE THREAD

**Issue by twilson63** [hyper63/hyper#372]
The nodejs implementation for hyper connect should work with typescript, esm, commonjs, and vite. This issue is to refactor the current connect repo into two repos, a `nodejs` and a `deno` repo, both will be typescript to take advantage of autocomplete for VS Code users and Typescript Users.

- [x] Data
- [x] Cache
   - [x] add
   - [x] get
   - [x] set
   - [x] remove
   - [x] query
- [x] Search

- [x] Migrate Tests
  - [x] Data
  - [x] Cache
  - [x] Search
   
- [x] Deno
- [ ] #373

**Comment by twilson63** [comment]
I was able to get a build together that supports all four platforms

- typescript
- esm
- cjs
- vite/esbuild

Need to migrate to this repository and migrate tests to validate code

**Comment by TillaTheHun0** [comment]
The code looks good to me, besides some TS specific things that i'll detail below. I see you've switched to using closures instead of ADTs, which I think is a fine tradeoff for now, until we figure out how to get crocks working. Here are some things that I noticed about the types and some potential solutions:

1. There is a TS error [here](https://github.com/hyper63/hyper/blob/618991047f4d3c5605b00a0e5a12dae8ba4be634/packages/connect/src/utils/hyper-request.ts#L60) because `params` is of type `unknown`. But we do know what `params` will be: `undefined | Record<string, any>`. So with `params` typed as `params?: Record<string, any>`, the error is resolved. We use `any` here because URLSearchParams does casting of types like `number` and `boolean` for us. So I think any is acceptable here. This also solves an issue [here](https://github.com/hyper63/hyper/blob/a0bb8849e808d2039da8acc86450e9a0cb917bd0/packages/connect/src/services/data.ts#L29)

2.  There is a TS error [here](https://github.com/hyper63/hyper/blob/618991047f4d3c5605b00a0e5a12dae8ba4be634/packages/connect/src/utils/hyper-request.ts#L63) because `options` type is:
```ts
{
  body?: unknown;
  headers: Headers;
  method: Method; <-- TS Enum
}
```

and the implicit type returned is:
```ts
{
  body?: unknown;
  headers: {};
  method: string;
}
```

Changing to initializing options like this resolves the issue:
```ts
let options = {
  headers: new Headers({
    "Content-Type": "application/json",
  }),
  method: method ? method : Method.GET,
};
```

Enums are one of the "things" in TypeScript that actually compile down into JS. Enums are compiled into POJOs, so you can use them like a pojo. Though **Enums do some magic**, which I don't like, and then you have to use that enum _everywhere_ in code, when static strings, with autocomplete, is what you want. For those reasons, I usually avoid TS enums and opt to use literals [see here](https://github.com/hyper63/hyper/blob/af43bb0e7b2997b20ad6bc8bee047dd82a631d8e/packages/connect/engine/engine.ts#L19) OR arrays declared `as const`, then use `typeof Val[number]` [see here](https://github.com/hyper63/hyper/blob/af43bb0e7b2997b20ad6bc8bee047dd82a631d8e/packages/connect/engine/mod.ts#L5). Both compile down to JS, and the latter compiles the array down into the JS (because it is just an array), for reference in the JS output. Both have pros and cons, albeit small.

3. There is a TS error [here](https://github.com/hyper63/hyper/blob/618991047f4d3c5605b00a0e5a12dae8ba4be634/packages/connect/src/index.ts#L17) because `body` of type `unknown` is incompatible with `BodyInit | undefined`. Changing body to be of type `BodyInit` solves the issue, which seems kosher since you're already using `Headers` from `node-fetch` in that same type.

4. A bunch of TS errors in [this file](https://github.com/hyper63/hyper/blob/618991047f4d3c5605b00a0e5a12dae8ba4be634/packages/connect/src/index.ts#L36) on the promise chains. This is due to `h` being `(hr: HyperRequest) => Promise<Request>` and the service methods expecting `(hr: HyperRequest) => Request`. Changing `HyperRequestFunction` to return a `Promise<Request>` solves the issues.

5. A couple TS errors [here](https://github.com/hyper63/hyper/blob/618991047f4d3c5605b00a0e5a12dae8ba4be634/packages/connect/src/services/cache.ts#L21) because you're using the array as a functor to map over (clever btw). You can:

declare `service` as const:
```ts
const service = "cache" as const;
```

declare `method` as const:
```ts
method: "PUT" as const,
```

and declare ttl as `string | undefined`
```ts
const includeTTL = (ttl: string | undefined) =>
```

6. Lots of TS errors in the test files, but I think the only thing worth fixing is `await`ing the return of the service methods, since they are meant to return promises. You can replace `identity` with `Promise.resolve` 

You can see these suggestions on `tillathehun0/feat-connect-372-ts-amendments` if that is easier to grok

**Comment by TillaTheHun0** [comment]
One final comment:

in `types.ts` you've used both `Type` and `T`. Then, that type is used sometimes used as the type of argument, sometimes as the output.

I would consider being more explicit. If the type is the return type, name the type something like `Result` or `R`. If the type if for the input arg, name it `Arg` or `Input`. Or perhaps name it to match the domain ie. data `Document` and cache `Value`.

Just a thought.

**Comment by twilson63** [comment]
Awesome, thank you for taking the time to review and the helpful typescript hints
